"""Atualiza o ID do usuario e chaves estrangeiras para UUID

Revision ID: 4942b33c3674
Revises: 
Create Date: 2025-06-27 18:43:25.696456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy_utils import UUIDType

# revision identifiers, used by Alembic.
revision = '4942b33c3674'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # This project previously relied on db.create_all(). Make the migration chain
    # usable for a new database while preserving the original upgrade path.
    if 'user' not in sa.inspect(op.get_bind()).get_table_names():
        op.create_table('user',
            sa.Column('id', UUIDType(binary=False), primary_key=True),
            sa.Column('username', sa.String(80), nullable=False, unique=True),
            sa.Column('password_hash', sa.String(120), nullable=False),
            sa.Column('is_banned', sa.Boolean(), nullable=False, server_default=sa.false()),
            sa.Column('banned_at', sa.DateTime()), sa.Column('created_at', sa.DateTime()),
            sa.Column('is_premium', sa.Boolean(), nullable=False, server_default=sa.false()),
            sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
        op.create_table('user_profile',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('user_id', UUIDType(binary=False), sa.ForeignKey('user.id'), nullable=False, unique=True),
            sa.Column('age', sa.Integer()), sa.Column('gender', sa.String(10)), sa.Column('goal', sa.String(100)),
            sa.Column('activity_level', sa.String(50)), sa.Column('dietary_restrictions', sa.Text()),
            sa.Column('weight', sa.Float()), sa.Column('height', sa.Float()), sa.Column('created_at', sa.DateTime()), sa.Column('updated_at', sa.DateTime()))
        op.create_table('diet_entry',
            sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', UUIDType(binary=False), sa.ForeignKey('user.id'), nullable=False),
            sa.Column('date', sa.Date(), nullable=False), sa.Column('meal_type', sa.String(50), nullable=False), sa.Column('description', sa.Text(), nullable=False),
            sa.Column('calories', sa.Float()), sa.Column('protein', sa.Float()), sa.Column('carbs', sa.Float()), sa.Column('fat', sa.Float()), sa.Column('notes', sa.Text()), sa.Column('created_at', sa.DateTime()))
        op.create_table('measurement',
            sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', UUIDType(binary=False), sa.ForeignKey('user.id'), nullable=False), sa.Column('date', sa.Date(), nullable=False),
            sa.Column('weight', sa.Float()), sa.Column('height', sa.Float()), sa.Column('body_fat', sa.Float()), sa.Column('muscle_mass', sa.Float()), sa.Column('waist', sa.Float()), sa.Column('chest', sa.Float()), sa.Column('arm', sa.Float()), sa.Column('thigh', sa.Float()), sa.Column('notes', sa.Text()), sa.Column('created_at', sa.DateTime()))
        op.create_table('chat_message',
            sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', UUIDType(binary=False), sa.ForeignKey('user.id'), nullable=False), sa.Column('message', sa.Text(), nullable=False), sa.Column('response', sa.Text(), nullable=False), sa.Column('created_at', sa.DateTime()))
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('diet_entry', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('banned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['username'])

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.drop_column('height')
        batch_op.drop_column('weight')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('banned_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('diet_entry', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    # ### end Alembic commands ###
